# Generated by Django 5.0.3 on 2024-03-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_task_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(max_length=255, null=True),
        ),
    ]
